---
title: Tidyverse and GGplot Guide # Title of the document

# Bibliography Details
bibliography: Tidyverse-GGplot-Guide.bib  # Name of bib file in the same folder 
bibliographystyle: apa            # Bibliography style

execute:               # Default settings for code blocks
  warning: false       # Do not print warnings
  message: false       # Do not print messages
  size: "scriptsize"   # Set code size to script size

# Below will do html by default. To render the entire project
# Use the following code:
# quarto::quarto_render("Lab10WriteUp.qmd")
format:
  pdf:        # Specify .pdf formatting options 
    documentclass: article     # Document Class
    number-sections: true      # Number Sections
    reference-section-title: "References" # Title for reference section
    code-line-numbers: true    # Line numbers printed in code
    cap-location: top          # Captions at the top of tables 
    geometry:
      - top=0.75in
      - left=0.75in
      - bottom=0.75in
      - right=0.75in
  html:       # Specify HTML formatting options 
    number-sections: true      # Number Sections
    code-fold: true            # Button to show code
    code-line-numbers: true    # Line numbers printed in code
    cap-location: top          # Captions at the top of tables and figures
format-links: [pdf]
---

```{r}
#| echo: false

default_chunk_hook  <- knitr::knit_hooks$get("chunk")

latex_font_size <- c("Huge", "huge", "LARGE", "Large", 
                     "large", "normalsize", "small", 
                     "footnotesize", "scriptsize", "tiny")

knitr::knit_hooks$set(chunk = function(x, options) {
  x <- default_chunk_hook(x, options)
  if(options$size %in% latex_font_size) {
    paste0("\n \\", options$size, "\n\n", 
      x, 
      "\n\n \\normalsize"
    )
  } else {
    x
  }
})
```

```{r}
#| label: load-packages
#| include: false
library(tidyverse)
library(patchwork)
library(pwr)
library(readxl)
library(dplyr)
library(kableExtra)
```



# Starting Tidyverse
